In [2]:
import numpy as np

In [35]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[0] + arr[5]

7

In [40]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
matriz[0]

array([1, 2, 3])

In [42]:
matriz[0,2]

3

In [43]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[0:3]

array([1, 2, 3])

In [45]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [46]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [47]:
arr[::2]

array([1, 3, 5, 7, 9])

In [48]:
arr[-1]

9

In [49]:
arr[-3:]

array([7, 8, 9])

In [51]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [56]:
matriz[1: , 0:2]

array([[4, 5],
       [7, 8]])

In [58]:
tridimencional =    [[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]]
tridimencional = np.array(tridimencional)
tridimencional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [63]:
tridimencional[1: , :2 , 2]

array([[12, 15],
       [21, 24]])