In [1]:
import numpy as np

In [5]:
scalar = np.array(12)
print(scalar)
scalar.ndim

12


0

In [8]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


3

In [14]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [20]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


hacer un tensor con 5 dimensiones, agregarle 1 y eliminar las que no se utilicen.

In [28]:
tensor = np.array([1,2,3], ndmin = 5)
print(tensor, tensor.ndim)
tensor = np.expand_dims(tensor, axis=0)
print(tensor, tensor.ndim)
tensor = np.squeeze(tensor)
print(tensor, tensor.ndim)

[[[[[1 2 3]]]]] 5
[[[[[[1 2 3]]]]]] 6
[1 2 3] 1
