In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,2))

In [7]:
arr.shape

(3, 2)

In [8]:
arr

array([[9, 4],
       [4, 8],
       [3, 8]])

In [9]:
arr.reshape(1,6)

array([[9, 4, 4, 8, 3, 8]])

In [12]:
arr.reshape(2,3)

array([[9, 4, 4],
       [8, 3, 8]])

In [13]:
np.reshape(arr,(1,6))

array([[9, 4, 4, 8, 3, 8]])

In [14]:
arr

array([[9, 4],
       [4, 8],
       [3, 8]])

In [16]:
np.reshape(arr,(2,3),'C')

array([[9, 4, 4],
       [8, 3, 8]])

In [17]:
np.reshape(arr,(2,3),'F')

array([[9, 3, 8],
       [4, 4, 8]])

In [18]:
np.reshape(arr,(2,3),'A')

array([[9, 4, 4],
       [8, 3, 8]])

In [26]:
reto = np.random.randint(1,10,(2,3))
print(reto, reto.shape)
reto = np.reshape(reto, (3,2))
print(reto, reto.shape)

[[4 6 9]
 [4 7 9]] (2, 3)
[[4 6]
 [9 4]
 [7 9]] (3, 2)
