In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,20,10)
arr

array([ 5,  7, 14,  1,  3, 17,  2,  9, 11, 13])

In [8]:
matriz = arr.reshape(2,5)
matriz

array([[ 5,  7, 14,  1,  3],
       [17,  2,  9, 11, 13]])

In [10]:
arr.max()

17

In [11]:
matriz

array([[ 5,  7, 14,  1,  3],
       [17,  2,  9, 11, 13]])

In [14]:
matriz.max(1)

array([14, 17])

In [15]:
arr.argmax()

5

In [18]:
matriz.argmax(1)

array([2, 0])

In [20]:
arr

array([ 5,  7, 14,  1,  3, 17,  2,  9, 11, 13])

In [19]:
arr.ptp()

16

In [21]:
matriz

array([[ 5,  7, 14,  1,  3],
       [17,  2,  9, 11, 13]])

In [25]:
matriz.ptp(0)

array([12,  5,  5, 10, 10])

In [27]:
np.percentile(arr,50)

8.0

In [30]:
arr.sort()
arr

array([ 1,  2,  3,  5,  7,  9, 11, 13, 14, 17])

In [32]:
np.median(arr)

8.0

In [34]:
np.std(arr)

5.2115256883181535

In [35]:
np.var(arr)

27.160000000000004

In [37]:
np.mean(arr)

8.2

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [46]:
b = np.expand_dims(b,axis=0)
b.ndim

2

In [48]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])