In [2]:
import numpy as np

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
trozo_de_arr = arr[:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [7]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [8]:
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [11]:
arr_copy = arr.copy()
arr_copy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [12]:
arr_copy[:] = 100

In [13]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])