In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [6]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [10]:
arr[(arr < 5)] = 99
arr

array([99, 99, 99, 99,  5,  6,  7,  8,  9, 10], dtype=int8)

In [11]:
reto = np.random.randint(1,100,(10,10))
reto

array([[19, 59, 18, 65, 18, 18, 91, 94, 93, 41],
       [60, 32,  4, 13, 86, 41, 13, 58, 32, 70],
       [96,  7, 16, 15, 95, 44, 67,  9, 43, 51],
       [87, 67, 98, 30, 84, 25, 69,  9, 49, 90],
       [72, 72, 36,  9, 99, 89, 43, 95, 96, 13],
       [97, 70, 31, 73, 79, 91, 84,  9, 50, 41],
       [37, 56, 43, 48, 82, 47, 71, 26,  1, 88],
       [30, 94, 83, 91, 64, 11, 74, 69, 14, 62],
       [66, 43, 77, 20,  4, 96, 98, 95, 34, 42],
       [88, 95, 31, 97, 66, 44,  1, 74, 32, 48]])

In [16]:
reto_copia = reto.copy()
reto_copia

array([[19, 59, 18, 65, 18, 18, 91, 94, 93, 41],
       [60, 32,  4, 13, 86, 41, 13, 58, 32, 70],
       [96,  7, 16, 15, 95, 44, 67,  9, 43, 51],
       [87, 67, 98, 30, 84, 25, 69,  9, 49, 90],
       [72, 72, 36,  9, 99, 89, 43, 95, 96, 13],
       [97, 70, 31, 73, 79, 91, 84,  9, 50, 41],
       [37, 56, 43, 48, 82, 47, 71, 26,  1, 88],
       [30, 94, 83, 91, 64, 11, 74, 69, 14, 62],
       [66, 43, 77, 20,  4, 96, 98, 95, 34, 42],
       [88, 95, 31, 97, 66, 44,  1, 74, 32, 48]])

numeros pares

In [18]:
pares = reto_copia[(reto_copia %2 == 0)]

array([18, 18, 18, 94, 60, 32,  4, 86, 58, 32, 70, 96, 16, 44, 98, 30, 84,
       90, 72, 72, 36, 96, 70, 84, 50, 56, 48, 82, 26, 88, 30, 94, 64, 74,
       14, 62, 66, 20,  4, 96, 98, 34, 42, 88, 66, 44, 74, 32, 48])

In [19]:
impares = reto_copia[(reto_copia %2 !=0)]
impares

array([19, 59, 65, 91, 93, 41, 13, 41, 13,  7, 15, 95, 67,  9, 43, 51, 87,
       67, 25, 69,  9, 49,  9, 99, 89, 43, 95, 13, 97, 31, 73, 79, 91,  9,
       41, 37, 43, 47, 71,  1, 83, 91, 11, 69, 43, 77, 95, 95, 31, 97,  1])