In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

In [4]:
lista * 2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_2 = arr.copy()

In [8]:
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
1 / arr

/tmp/ipykernel_14912/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
matriz = arr.reshape(2,5)
matriz_2 = matriz.copy()

In [19]:
matriz + matriz_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
np.matmul(matriz, matriz_2.T)

array([[ 30,  80],
       [ 80, 255]])

In [22]:
matriz @ matriz_2.T

array([[ 30,  80],
       [ 80, 255]])