In [1]:
import numpy as np


Scalar

In [5]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

Vector

In [7]:
x = np.array([42,22,12])
print(x.shape)
x.ndim

(3,)


1

Matrix

In [9]:
x = np.array([[42,22,12],[42,22,12]])
print(x.shape)
x.ndim

(2, 3)


2

Tensor

In [10]:
x = np.array([[[42,22,12],[42,22,12]],
 [[42,22,12],[42,22,12]],
  [[42,22,12],[42,22,12]]])
print(x.shape)
x.ndim

(3, 2, 3)


3

Reshape

In [12]:
x = np.array([[0,1],
          [2,3],
          [4,5],
          [6,7],
          ])
x.shape

(4, 2)

In [13]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [14]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

transpuesta

In [15]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [16]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])